#!/usr/bin/env python3
"""Regenerate src/ephemvis/_fontdata.py from the astroglyphs_2K toolkit (build-time only).

ephemvis vendors the toolkit's Astroglyphs 2K font data into a self-contained module so ephemvis keeps
zero runtime dependencies while embedding deterministic, OFL glyphs in every SVG. Re-run this
whenever astroglyphs_2K is updated:

    pip install -e ../astroglyphs_2K        # or the published package
    python tools/refresh_fontdata.py
"""
from __future__ import annotations

import pathlib

import astroglyphs_2K as ag

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "ephemvis" / "_fontdata.py"

L: list[str] = [
    f'"""Generated by tools/refresh_fontdata.py from astroglyphs_2K {ag.__version__} — DO NOT EDIT.',
    "",
    "Embedded OFL glyph data (the astroglyphs_2K 'Astroglyphs 2K' font: symbols and text in one",
    "family), inlined into every SVG so glyphs render deterministically regardless of the viewer's",
    "fonts. Code is MIT; the font is built from Noto under the SIL Open Font License 1.1 — see",
    "LICENSES/OFL.txt. ephemvis has no runtime dependency on the toolkit; regenerate with",
    "tools/refresh_fontdata.py.",
    '"""',
    "# ruff: noqa: E501",
    f"FAMILY_NAME = {ag.FAMILY_NAME!r}",
    f"SYM_FAMILY = {ag.SYM_FAMILY!r}",
    f"TXT_FAMILY = {ag.TXT_FAMILY!r}",
    f"OFL_ATTRIBUTION = {ag.OFL_ATTRIBUTION!r}",
    f"_WOFF2_B64 = {ag.WOFF2_B64!r}",
    "",
    "# name -> codepoints, default form first (e.g. 'pluto': ♇ ⯓ ⯔ ⯕ ⯖)",
    "ALTERNATES = {",
]
L += [f"    {k!r}: [{', '.join(f'0x{c:04X}' for c in v)}]," for k, v in ag.ALTERNATES.items()]
L += ["}", "# Hermetic lots, contiguous Private Use block in Paulus order",
      "LOTS = {"]
L += [f"    {k!r}: 0x{v:04X}," for k, v in ag.LOTS.items()]
L += ["}", "# codepoint -> (advance, ymin, ymax, xmin, xmax) as fractions of em (ink bbox)",
      "GLYPH_METRICS = {"]
L += [f"    0x{cp:04X}: {ag.GLYPH_METRICS[cp]!r}," for cp in sorted(ag.GLYPH_METRICS)]
L += ["}", "", "",
      "def font_face_css() -> str:",
      '    """A <style> element inlining the embedded font as a data: woff2 URI (self-contained)."""',
      "    return ('<style>@font-face{font-family:\"%s\";src:url(data:font/woff2;base64,%s) '",
      "            'format(\"woff2\");font-weight:100 900;}</style>' % (FAMILY_NAME, _WOFF2_B64))",
      ""]

OUT.write_text("\n".join(L), encoding="utf-8")
print(f"wrote {OUT}  ({OUT.stat().st_size // 1024} KB)  metrics for {len(ag.GLYPH_METRICS)} glyphs")
