#!/usr/bin/env python3
"""Regenerate src/ephemvis/_fontdata.py from the astroglyphs_2K toolkit (build-time only).

ephemvis vendors the toolkit's *astroset* data into a self-contained module so ephemvis keeps
zero runtime dependencies while embedding deterministic, OFL glyphs in every SVG. Re-run this
whenever astroglyphs_2K is updated:

    pip install -e ../astroglyphs_2K        # or the published package
    python tools/refresh_fontdata.py
"""
from __future__ import annotations

import pathlib

import astroglyphs_2K as ag

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "ephemvis" / "_fontdata.py"

L: list[str] = [
    f'"""Generated by tools/refresh_fontdata.py from astroglyphs_2K {ag.__version__} — DO NOT EDIT.',
    "",
    "Embedded OFL glyph data (the astroglyphs_2K 'astroset'), inlined into every SVG so glyphs",
    "render deterministically regardless of the viewer's fonts. Code is MIT; these glyphs are",
    "subset from Noto under the SIL Open Font License 1.1 — see LICENSES/OFL.txt. ephemvis has no",
    "runtime dependency on the toolkit; regenerate with tools/refresh_fontdata.py.",
    '"""',
    "# ruff: noqa: E501",
    f"SYM_FAMILY = {ag.SYM_FAMILY!r}",
    f"TXT_FAMILY = {ag.TXT_FAMILY!r}",
    f"OFL_ATTRIBUTION = {ag.OFL_ATTRIBUTION!r}",
    f"_SYMBOL_FAMILY_NAMES = {ag.SYMBOL_FAMILY_NAMES!r}",
    f"_TEXT_FAMILY_NAME = {ag.TEXT_FAMILY_NAME!r}",
    "_SYMBOLS_WOFF2_B64 = [",
]
L += [f"    {b!r}," for b in ag.SYMBOLS_WOFF2_B64]
L += ["]", f"_TEXT_WOFF2_B64 = {ag.TEXT_WOFF2_B64!r}", ""]
L += ["# codepoint -> (advance, ymin, ymax, xmin, xmax) as fractions of em (ink bbox)",
      "GLYPH_METRICS = {"]
L += [f"    0x{cp:04X}: {ag.GLYPH_METRICS[cp]!r}," for cp in sorted(ag.GLYPH_METRICS)]
L += ["}", "", "",
      "def font_face_css() -> str:",
      '    """A <style> element inlining the embedded fonts as data: woff2 URIs (self-contained)."""',
      "    faces = []",
      "    for fam, b64 in zip(_SYMBOL_FAMILY_NAMES, _SYMBOLS_WOFF2_B64, strict=True):",
      "        faces.append('@font-face{font-family:\"%s\";src:url(data:font/woff2;base64,%s) '",
      "                     'format(\"woff2\");}' % (fam, b64))",
      "    faces.append('@font-face{font-family:\"%s\";src:url(data:font/woff2;base64,%s) '",
      "                 'format(\"woff2\");font-weight:100 900;}' % (_TEXT_FAMILY_NAME, _TEXT_WOFF2_B64))",
      '    return "<style>" + "".join(faces) + "</style>"',
      ""]

OUT.write_text("\n".join(L), encoding="utf-8")
print(f"wrote {OUT}  ({OUT.stat().st_size // 1024} KB)  metrics for {len(ag.GLYPH_METRICS)} glyphs")
